baseURL = "/"
languageCode = "en-us"
title = "Apriil15"
theme ="archie"
copyright = "© Apriil15"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 3 # articles per page

# Disqus
disqusShortname = "apriil15"

[params]
	mode="auto" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "三分鐘熱度！"

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/Apriil15"

# [[params.social]]
# name = "Twitter"
# icon = "twitter"
# url = "https://twitter.com/athulcajay/"

# [[params.social]]
# name = "GitLab"
# icon = "gitlab"
# url = "https://gitlab.com/athul/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4